# Generated by Django 3.2.4 on 2021-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('station_id', models.CharField(max_length=256)),
                ('action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
